= Inline Images

This plugin adds support for inline images via http://en.wikipedia.org/wiki/Data_URI_scheme[data URIs]. This is useful for situations where the images you need to embed in a rendered PDF or image are not accessible via a URL.

For example, your application may generate barcodes that you don't necessarily want to expose but want to include in your generated PDFs or images. Using inline images, you can include the image bytes directly in the output.

To make this easier, the plugin provides tags to render byte arrays as common image formats (i.e. gif, png and jpeg).

The tags are under the namespace `rendering` and are called `inlinePng`, `inlineGif` and `inlineJpeg`. They all take a single argument, `bytes`, which is a `byte[]` containing the raw bytes of the image.

Here is an example of how this could be used to include a local (i.e. from the filesystem) image in a generated pdf/image.

[source,groovy]
----
class SomeController {
    
    def generate() {
        URL resource = this.class.getResource("/path/to/image.png")
        renderPng(template: "thing", model: [imageBytes: resource.bytes])
    } 
}
----

In the view ...

[source,html]
._thing.gsp
----
<html>
    <head></head>
    <body>
        <p>Below is an inline image</p>
        <rendering:inlinePng bytes="${imageBytes}" class="some-class" />
    </body>
</html>
----
